freebsd: resizefs, add support for newfs -L argumet
newfs -L argument is used to specify a label for the new filesystem.

Without this patch, cc_resizefs.py returns the following error:

```
2019-04-19 15:40:28,010 - util.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/local/lib/python2.7/site-packages/cloud_init-18.5-py2.7.egg/cloudinit/config/cc_resizefs.py'>) failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cloud_init-18.5-py2.7.egg/cloudinit/stages.py", line 812, in _run_modules
    freq=freq)
  File "/usr/local/lib/python2.7/site-packages/cloud_init-18.5-py2.7.egg/cloudinit/cloud.py", line 54, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/local/lib/python2.7/site-packages/cloud_init-18.5-py2.7.egg/cloudinit/helpers.py", line 187, in run
    results = functor(*args)
  File "/usr/local/lib/python2.7/site-packages/cloud_init-18.5-py2.7.egg/cloudinit/config/cc_resizefs.py", line 271, in handle
    if can_skip_resize(fs_type, resize_what, devpth):
  File "/usr/local/lib/python2.7/site-packages/cloud_init-18.5-py2.7.egg/cloudinit/config/cc_resizefs.py", line 165, in can_skip_resize
    return func(resize_what, devpth)
  File "/usr/local/lib/python2.7/site-packages/cloud_init-18.5-py2.7.egg/cloudinit/config/cc_resizefs.py", line 114, in _can_skip_resize_ufs
    optlist, _args = getopt.getopt(newfs_cmd[1:], opt_value)
  File "/usr/local/lib/python2.7/getopt.py", line 90, in getopt
    opts, args = do_shorts(opts, args[0][1:], shortopts, args[1:])
  File "/usr/local/lib/python2.7/getopt.py", line 190, in do_shorts
    if short_has_arg(opt, shortopts):
  File "/usr/local/lib/python2.7/getopt.py", line 206, in short_has_arg
    raise GetoptError('option -%s not recognized' % opt, opt)
GetoptError: option -L not recognized
```